# Setup
title:               James' Site
tagline:             'My thoughts and projects'
description:         'A site for organizing thoughts, projects, and data.'
url:                 https://james-herbstritt.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James Herbstritt
  url:               https://github.com/james-herbstritt
  email:             james.herbstritt@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
